@startuml
class Bornes {
-int kms
}
abstract class Parade{}
abstract class Botte{}
abstract class Attaque{}

interface Iterable<T> {
    + iterator() : Iterator<T>
}

interface Strategie {
    + String choisirCoup(Jeu jeu)
    + String toString()
}

class StrategieFacile {
    + String choisirCoup(Jeu jeu)
    + String toString()
}

class StrategieBasique {
    + String choisirCoup(Jeu jeu)
    + String toString()
}

class StrategieTrivial {
    + String choisirCoup(Jeu jeu)
    + String toString()
}

class StrategieDifficile {
    + String choisirCoup(Jeu jeu)
    + String toString()
    - ArrayList<String> genererCoupsPossibles(Jeu jeu)
    - int evaluerCoup(String coup, Joueur joueurCourant)

}

class CollectionJoueurs {
    + CollectionJoueurs(int nbJoueurs)
    + CollectionJoueurs(CollectionJoueurs cj)
    + void ajouter(Joueur j)
    + int size()
    + Joueur get(int no)
    + String toString()
    + Iterator<Joueur> iterator()
    + String toString()
}

abstract class Joueur {
    - String nom
    - int bornes
    - int cartes200Jouees
    - boolean limitationVitesse
    - int cartes200Jouees
    + void Joueur(Jeu jeu, String nom)
    + void Joueur(Jeu jeu, String nom, Bottes bottes, Carte bataille)
    + void Joueur(Joueur j)
    + PaquetDeCartes getMain()
    + int getNbCartesMain()
    + String getNom()
    + void ajouterMain(Carte carte)
    + void retirerMain(Carte carte)
    + void setJeu(Jeu jeu)
    + boolean peutRecevoir(Accident accident)
    + boolean peutRecevoir(FeuRouge feuRouge)
    + boolean peutRecevoir(Crevaison crevaison)
    + boolean peutRecevoir(PanneDEssence panneDEssence)
    + boolean peuRecevoir(LimitationDeVitesse limitationDeVitesse)
    + boolean estPossiblePoser(FeuVert feuVert)
    + boolean estPossiblePoser(Reparation reparation)
    + boolean estPossiblePoser(Essence essence)
    + boolean estPossiblePoser(RoueDeSecours roueDeSecours)
    + boolean estPossiblePoser(FinLimitationDeVitesse finLimitationDeVitesse)
    + void setLimitationVitesse()
    + boolean estPossiblePoser(Bornes bornes)
    + void setBataille(Carte newBataille)
    + void setBottes(Bottes newBottes)
    + abstract Joueur clone()
    + void jouerCoup(coup)
    + abstract void jouer(String coup)
    + boolean coupPossible(String coup)
    + Carte getBataille()
    - void jouerJeuAdverse(Carte carte, Joueur joueurAdverse)
    - void jouerPoserSurMonJeu(Carte carte)
    - void activerBotte(Carte carte)
    - void jouerJeter(Carte carte)
    - boolean coupJxPossible(String coup)
    - boolean coupPxPossible(String coup)
    - boolean coupPxyPossible(String coup)
    + String toString()
    + public boolean estBot()
    + public boolean estHumain()
}

class Jeu {
    - int joueurQuiJoue
    - int joueurQuiDistribue
    + Jeu()
    + Jeu(Joueur j)
    + void jeter(Carte c)
    + void add(Joueur j)
    + int getNbJoueurs()
    + int getJoueurQuiDistribue()
    + int getJoueurQuiJoue()
    + void setJoueurQuiJoue()
    + Joueur getJoueur(int indiceJoueur)
    + String toString()
    + void jouer(String coup)
    + boolean coupPossible(String coup)
    + void initialiser(int nbBots)
    - void choisirQuiJoue()
    - void choisirQuiDistribue()
    - void distribuer()
    + void donnerCarte((Joueur j)
    - creerJoueurs(int nbJoueurs)
    + boolean estTermine()
    - void determinerGagnantParProximite()
    + Iterator<Joueur> iterator()
    + String toString()
}

class PaquetDeCartes {
    + PaquetDeCartes()
    + PaquetDeCartes(Carte... cartes)
    + PaquetDeCartes(PaquetDeCartes pdc)
    + int getNbCartes()
    + Carte getCarte(int no)
    + void ajouter(Carte... cartes)
    + void ajouter(PaquetDeCartes pdc)
    +  boolean estVide()
    + void melanger()
    + void retourner()
    + Carte getSommet()
    + void enlever(Carte carte)
    + Carte piocher()
    + void ecrire(String nomDeFichier) throws ErreurFichier
    - Map<String, Integer> nbCarteDeChaqueType()
    + void lire(String nomDeFichier) throws ErreurFichier
    + int nombreOccurrences(Carte carte)
    + Iterator<Carte> iterator()
    + String toString()

}

abstract class Carte {
    + boolean peutEtrePoseeSurMonJeu(Joueur j)
    + boolean peutEtrePoseeSurJeuAdversaire(Joueur j)
    + boolean match(String s)
    + boolean estUneAttaque()
    + boolean estUneParade()
    + String toString()
}

class Bottes {
    - boolean estAsDuVolant
    - boolean estPrioritaire
    - boolean estCiterneDEssence
    - boolean estIncrevable
    + boolean estAsDuVolant()
    + boolean estPrioritaire()
    + boolean estCiterneDEssence()
    + boolean estIncrevable()
    + void setPrioritaire()
    + void setAsDuVolant()
    + void setCiterneDEssence()
    + void setIncrevable()
}

class CollectionJeux {
    + CollectionJeux()
    + void add(Jeu jeu)
    + void add(CollectionJeux cj)
    + void remove(Jeu jeu)
    + void remove(CollectionJeux cj)
    + int size()
    + Iterator<Joueur> iterator()
    + String toString()
}

class FabriqueJeux {
    + {static} CollectionJeux creerJeuUnJoueur(nom : String, cT : Carte[], cM : Carte[], b : Bottes[])
    + {static} CollectionJeux getMB1JReparationCorrect()
    + {static} CollectionJeux getMB1JAccidentCorrect()
    + {static} CollectionJeux getMB1JFeuVertCorrectSansAsDuVolant()
    + {static} CollectionJeux getMB2JAccidentCorrect()
    - {static} Jeu combiner(jeu1 : Jeu, jeu2 : Jeu)
}

class FabriqueBottes {
    + {static} Bottes[] getToutesLesBottesPossibles()
    + {static} Bottes[] getToutesLesBottesPossiblesSaufAsDuVolant()
    - {static} Bottes creerBottes(estAsDuVolant : boolean, estPrioritaire : boolean, estCiterneDEssence : boolean, estIncrevable : boolean)
}

class FabriqueCartes {
    + {static} PaquetDeCartes getPaquetVide()
    + {static} PaquetDeCartes getPaquetBottes()
    + {static} PaquetDeCartes getPaquet1Accident()
    + {static} PaquetDeCartes getPaquet1FeuRouge1FeuVert()
    + {static} PaquetDeCartes getPaquetStandard()
    + {static} PaquetDeCartes getPaquetStandardManuel()
}

class DialogueLigneDeCommande{
    + void reagir()
    + int definirNbBots()
    + Strategie demanderStrategieBot(int indexBot, int nbBots)
    - void afficherFinDuJeu()
    - String getCoupJoueurHumain()
    - void afficherEtatJeu()
}

class Bot{
    + Bot(Jeu jeu, String nom, Strategie strategie)
    + Bot(Bot j)
    + Bot clone()
    + boolean estBot()
    + void jouer(String coup)
}

class JoueurHumain {
    + JoueurHumain(Jeu jeu, String nom)
    + public JoueurHumain(Jeu jeu, String nom, Bottes bottes, Carte bataille)
    +  boolean estHumain()
    + JoueurHumain(JoueurHumain j)
    + JoueurHumain clone()
    + void jouer(String coup)
    }

' Relations entre les classes
CollectionJoueurs -- "*" Joueur : cj
Jeu -- "1" CollectionJoueurs
Joueur "1" -- Jeu : joueurGagnant
Joueur -- "1" Jeu
Joueur -- "1" PaquetDeCartes : main
Jeu -- "1" PaquetDeCartes : talon
Jeu -- "1" PaquetDeCartes : pioche
Jeu -- "1" DialogueLigneDeCommande
DialogueLigneDeCommande -- "1" Jeu
PaquetDeCartes -- "*" Carte
Joueur -- "1" Carte : bataille
Joueur -- "1" Bottes : bottes

Bot -- "1" Strategie

'pour les cartes
LimitationDeVitesse --|> Carte
FinLimitationDeVitesse --|> Carte

Parade -right-|> Carte
Botte -up-|> Carte
Attaque -left-|> Carte
Bornes -up-|> Carte

FeuRouge -up-|> Attaque
Crevaison -up-|> Attaque
PanneDEssence -up-|> Attaque
Accident -up-|> Attaque

FeuVert -up-|> Parade
RoueDeSecours -up-|> Parade
Essence -up-|> Parade
Reparation -up-|> Parade

Prioritaire -up-|> Botte
Increvable -up-|> Botte
CiterneDEssence -up-|> Botte
AsDuVolant -up-|> Botte

JoueurHumain -right-|> Joueur
Bot -right-|> Joueur

PaquetDeCartes .up.|> Iterable
CollectionJoueurs .up.|> Iterable
CollectionJeux .up.|> Iterable
Jeu .|> Iterable

StrategieFacile .up.|> Strategie
StrategieBasique .up.|> Strategie
StrategieTrivial .up.|> Strategie
StrategieDifficile .up.|> Strategie


@enduml
